# docker run --rm -it -v local_storage:/imagen_storege --name name_imagen id_imagen /bin/zsh
FROM kalilinux/kali-rolling:latest
LABEL jsg <hajorge2012@gmail.com>

# Update
RUN apt-get -y update && apt-get -y dist-upgrade && apt-get -y autoremove && apt-get clean

# Working Directory
WORKDIR /root
RUN mkdir ${HOME}/tools && \
  mkdir -p /usr/share/wordlists

# Temporary solution, it is not safe, create a base password. Change it or use another way
RUN echo "root:root" | chpasswd

# Install Essentials
RUN apt-get install -y \
  build-essential \
  iputils-ping\
  git \
  neovim \
  wget \
  curl \
  make \
  python3 \
  python3-pip \
  perl \
  net-tools \
  zsh \
  tmux \
  metasploit-framework \
  sudo \
  enum4linux \
  gobuster \
  smbclient \
  smbmap \
  snmp \ 
  sslscan 

## Basic Tools installation
RUN apt-get install -y \
  rlwrap\
  ftp\
  openvpn \
  traceroute \
  whois \
  host \
  htop \
  dnsutils \
  figlet \
  tcpdump \
  telnet \
  unzip \
  p7zip-full \
  locate \
  tree \
  nmap \
  nikto \
  netcat \
  cewl \
  openssh-server \
  gcc \
  powerline \
  man-db

## non-root config
RUN adduser --home /home/test test
RUN usermod -a -G sudo test
RUN chsh -s /bin/zsh test
# Temporary solution, it is not safe, create a base password. Change it or use another way
RUN echo "test:test" | chpasswd

## zsh
WORKDIR /home/test
RUN git clone https://github.com/robbyrussell/oh-my-zsh.git /home/test/.oh-my-zsh && \
  cp /home/test/.oh-my-zsh/templates/zshrc.zsh-template /home/test/.zshrc && \
  chsh -s /bin/zsh && \
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "/home/test/.zsh-syntax-highlighting" --depth 1 && \
  echo "source /home/test/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> "/home/test/.zshrc"

RUN sed -i '1i export HISTFILE="/imagen_storege/.zsh_history"' /home/test/.zshrc

CMD /bin/zsh
USER test
